# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Setup, Install & Build
    before: yarn global add express
    init: yarn install # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: yarn build

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Website
    description: Website Preview
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
